### ISSUE TITLE
Add new functions realted to DALL-E end-point

### ISSUE THREAD

**Issue by irudnyts** [irudnyts/openai#17]
See details [here](https://beta.openai.com/docs/api-reference/images).

**Comment by 3SMMZRjWgS** [comment]
@irudnyts Thank you for publishing this R package! Would love to see DALL-E endpoint added at some point.

**Comment by irudnyts** [comment]
@3SMMZRjWgS Almost done, have a look at this branch: https://github.com/irudnyts/openai/tree/images
