### ISSUE TITLE
Returning error code?

### ISSUE THREAD

**Issue by isinaltinkaya** [irudnyts/openai#23]
Hi! I have been using this package, and I must say I really liked it and greatly appreciate it.

Is it possible for you to return a return code with the response indicating if the returned item is a real response or an error? After ChatGPT release the server started to give error messages instead of replies occasionally. It would be awesome if it was handled in openai package.

Thanks!

**Comment by irudnyts** [comment]
I was developing `{openai}` with this [principle](https://httr.r-lib.org/articles/api-packages.html#turn-api-errors-into-r-errors) in mind, i.e., if the error happens on the API side, I need to turn it into an R error with an explicit message. 

Your use-case can be solved with `tryCatch()` function: 

```
library(openai)

try_create_completion <- function(prompt) {
    tryCatch(
        create_completion(prompt),
        error = function(e) "Hey, something went wrong!" # if the error happens, this is what returned
    )
}

try_create_completion(34) # will print "Hey, something went wrong!" since it is
                          # not allowed to pass 34 as `prompt` argument

try_create_completion(34) # will be executed nomrally unless there is an issue
                          # on the server end
```

You can replace `"Hey, something went wrong!"` with `FALSE`, and this is going to be an indicator that there is an error.

Please let me know if this helps.
