### ISSUE TITLE
R >= 4.2 dependency

### ISSUE THREAD

**Issue by brunomioto** [irudnyts/openai#27]
Is it necessary?

Installing CRAN version on 4.1.1
```
Warning in install.packages :
  package ‘openai’ is not available for this version of R
```

Installing Github version on 4.1.1
```
ERROR: this R is version 4.1.1, package 'openai' requires R >= 4.2
```

**Comment by irudnyts** [comment]
It is not, but that was a requirement of CRAN (if I remember correctly). If you have to stick to 4.1.1, I suggest cloning the repo, changing 4.2 to 4.1 in `DESCRIPTION`, and installing the package from the source (**Install** button in **Build** section of RStudio).

**Comment by JamesHWade** [comment]
I think you are right about it requiring a minimum version of R, but you make be able to put an older version. Something like R >= 3.6.

**Comment by msberends** [comment]
Hi, just wanted to add - [our CRAN package relies/depends on R >= 3.0](https://cran.r-project.org/package=AMR), released in April 2013. CRAN does not require you to rely on the newest R, just that all your functions work in the lowest version number you want to rely on. 

I would advise to keep the R dependency number as low as possible to provide this package to as many users as possible. Thousands and thousands of R users are probably on older R versions - they cannot use `openai` at the moment.

**Comment by brunomioto** [comment]
Yeah, maybe CRAN suggested supporting 4.2, but not just 4.2. it's advised to not do it: https://r-pkgs.org/description.html#sec-description-imports-suggests

**Comment by irudnyts** [comment]
You're right, it is indeed not a requirement. In the next version, I will downgrade to 3.4 (the highest version in my imported packages).

**Comment by olyerickson** [comment]
Given the tremendous interest in ChatGPT et.al. right now, please consider fixing this ASAP.!!

**Comment by irudnyts** [comment]
The dependence is downgraded to R 3.5 (also available from CRAN).
