### ISSUE TITLE
unable to load shared object '/Users/jeroen/Lokaal/R/packages/curl/libs/curl.so'

### ISSUE THREAD

**Issue by abjeroen** [irudnyts/openai#32]
I get this error when I use the example command:
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/myname/Lokaal/R/packages/curl/libs/curl.so':
  dlopen(/Users/myname/Lokaal/R/packages/curl/libs/curl.so, 0x0006): tried: '/Users/myname/Lokaal/R/packages/curl/libs/curl.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/myname/Lokaal/R/packages/curl/libs/curl.so' (no such file), '/Users/myname/Lokaal/R/packages/curl/libs/curl.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

Not compatible with M1 macs yet?

**Comment by irudnyts** [comment]
Hi @abjeroen! Can you please specify the exact example that does not work (or even better, built up [a reproducible example ](http://adv-r.had.co.nz/Reproducibility.html))?

**Comment by abjeroen** [comment]
fixed. I had the wrong environment!
