### ISSUE TITLE
Allow for all other models for Chat endpoint (e.g., GPT-4)

### ISSUE THREAD

**Issue by irudnyts** [irudnyts/openai#35]
See the list of models here: [https://platform.openai.com/docs/models/model-endpoint-compatibility](https://platform.openai.com/docs/models/model-endpoint-compatibility)

**Comment by zhaohongxin0** [comment]
Needs to update the packages?

Error in match.arg(model) : 
  'arg' should be one of “gpt-3.5-turbo”, “gpt-3.5-turbo-0301”

**Comment by irudnyts** [comment]
@zhaohongxin0 Yep, and since version 0.4.1 is on CRAN already, you can simply `install.packages("openai")` to update.
