### ISSUE TITLE
Update for `gpt-3.5-turbo`

### ISSUE THREAD

**Issue by cbail** [irudnyts/openai#37]
Hi- thanks so much for the package. It seems like one of the URLs called in the create_completion() function may need to be updated for gpt-3.5-turbo. When I request it as a model option, I get the following error message:

`Error: OpenAI API request failed [404]:

This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?`

If you have the bandwidth to take this on, I'd be very grateful!

**Comment by irudnyts** [comment]
Hi @cbail, thanks for the question. There exists a stand-alone function for this: `create_chat_completion()`. Does that help?

**Comment by cbail** [comment]
Ah so sorry I should have found this by myself. Thanks for this great package!
