### ISSUE TITLE
[RStudio] Got an error message each time I try to use code autocomplete on openai library

### ISSUE THREAD

**Issue by tokumotion** [irudnyts/openai#53]
This is the error I get

> Error in fetch(key) : 
> lazy-load database '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/openai/help/openai.rdb' is corrupt
> 

You can see the screenshot also. I removed and reinstalled the library a couple of time, but this keeps happening.

![Screenshot 2023-12-13 at 19 11 40](https://github.com/irudnyts/openai/assets/10216916/19f82987-82f7-48a3-9749-bb5ded440b25)

Thanks

**Comment by irudnyts** [comment]
@tokumotion thanks for that. Hmm, what I would suggest is to give it a try and installing the dev version of the package: 

```
remotes::install_github("irudnyts/openai", ref = "r6")
```

And then, you can use it as: 

```
library(openai)
client <- OpenAI()
completion <- client$chat$completions$create(
    model = "gpt-3.5-turbo",
    messages = list(list("role" = "user", "content" = "What's up?"))
)
```

For the image, I will try (no commitments) do it this weekend :)

**Comment by irudnyts** [comment]
Please, let me know if it worked with the dev version.

**Comment by tokumotion** [comment]
> @tokumotion thanks for that. Hmm, what I would suggest is to give it a try and installing the dev version of the package:
> 
> ```
> remotes::install_github("irudnyts/openai", ref = "r6")
> ```
> 
> And then, you can use it as:
> 
> ```
> library(openai)
> client <- OpenAI()
> completion <- client$chat$completions$create(
>     model = "gpt-3.5-turbo",
>     messages = list(list("role" = "user", "content" = "What's up?"))
> )
> ```
> 
> For the image, I will try (no commitments) do it this weekend :)

Hi @irudnyts, just removed the last version of the library (which was working fine, only had that annoying error message) and reinstalled it as per your suggestion and I'm not seeing that error again, thanks!

I'll close this :)
